// examples/SqlOS.Example.AngularWeb/src/app/pages/retail/stores/stores.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';
import { PagedResponse, LocationDto } from '../../../models';

@Component({
  selector: 'app-stores',
  standalone: true,
  imports: [RouterLink, FormsModule],
  template: `
    <div class="gap-20">
      <div class="page-header">
        <h1>Stores</h1>
        <p>All store locations visible to your account.</p>
      </div>

      @if (error()) {
        <p class="error">{{ error() }}</p>
      }

      <div class="card">
        <div class="toolbar">
          <input type="text" placeholder="Search stores..." [ngModel]="search()" (ngModelChange)="onSearch($event)" class="toolbar-search">
          <span class="badge badge-neutral">{{ loading() ? '...' : stores().length + ' store' + (stores().length !== 1 ? 's' : '') }}</span>
        </div>

        @if (loading()) {
          <p class="muted" style="margin-top: 16px">Loading...</p>
        } @else if (stores().length === 0) {
          <div class="empty-state">
            <strong>No stores found</strong>
            <p>{{ search() ? 'Try a different search term.' : 'No stores visible with your current permissions.' }}</p>
          </div>
        } @else {
          <table class="data-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Store #</th>
                <th>Chain</th>
                <th>City</th>
                <th>State</th>
              </tr>
            </thead>
            <tbody>
              @for (s of stores(); track s.id) {
                <tr>
                  <td><a [routerLink]="'/retail/locations/' + s.id">{{ s.name }}</a></td>
                  <td class="mono">{{ s.storeNumber ?? '—' }}</td>
                  <td><a [routerLink]="'/retail/chains/' + s.chainId" class="muted">{{ s.chainName ?? s.chainId }}</a></td>
                  <td>{{ s.city ?? '—' }}</td>
                  <td>{{ s.state ?? '—' }}</td>
                </tr>
              }
            </tbody>
          </table>
        }
      </div>
    </div>
  `,
})
export class StoresComponent implements OnInit {
  private api = inject(ApiService);

  stores = signal<LocationDto[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);
  search = signal('');

  ngOnInit() {
    this.loadStores();
  }

  onSearch(value: string) {
    this.search.set(value);
    this.loadStores();
  }

  async loadStores() {
    this.loading.set(true);
    const params = new URLSearchParams({ pageSize: '50' });
    if (this.search()) params.set('search', this.search());
    try {
      const r = await this.api.get<PagedResponse<LocationDto>>(`/api/locations?${params}`);
      this.stores.set(r.data);
    } catch (e: any) {
      this.error.set(e.message);
    } finally {
      this.loading.set(false);
    }
  }
}

// examples/SqlOS.Example.Web/app/retail/stores/page.tsx
"use client";

import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import Link from "next/link";
import { apiGet } from "@/lib/api";

type PagedResponse<T> = { data: T[]; totalCount: number; hasMore: boolean };
type LocationDto = { id: string; resourceId: string; chainId: string; chainName?: string; name: string; storeNumber?: string; city?: string; state?: string; createdAt: string };

export default function StoresPage() {
  const { data: session } = useSession();
  const [stores, setStores] = useState<LocationDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");

  useEffect(() => {
    if (!session?.accessToken) return;
    setLoading(true);
    const params = new URLSearchParams({ pageSize: "50" });
    if (search) params.set("search", search);
    apiGet<PagedResponse<LocationDto>>(`/api/locations?${params}`, session.accessToken)
      .then((r) => setStores(r.data))
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [session?.accessToken, search]);

  return (
    <div className="gap-20">
      <div className="page-header">
        <h1>Stores</h1>
        <p>All store locations visible to your account.</p>
      </div>

      {error && <p className="error">{error}</p>}

      <div className="card">
        <div className="toolbar">
          <input type="text" placeholder="Search stores..." value={search} onChange={(e) => setSearch(e.target.value)} className="toolbar-search" />
          <span className="badge badge-neutral">{loading ? "..." : `${stores.length} store${stores.length !== 1 ? "s" : ""}`}</span>
        </div>

        {loading ? (
          <p className="muted" style={{ marginTop: 16 }}>Loading...</p>
        ) : stores.length === 0 ? (
          <div className="empty-state">
            <strong>No stores found</strong>
            <p>{search ? "Try a different search term." : "No stores visible with your current permissions."}</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Store #</th>
                <th>Chain</th>
                <th>City</th>
                <th>State</th>
              </tr>
            </thead>
            <tbody>
              {stores.map((s) => (
                <tr key={s.id}>
                  <td><Link href={`/retail/locations/${s.id}`}>{s.name}</Link></td>
                  <td className="mono">{s.storeNumber ?? "—"}</td>
                  <td><Link href={`/retail/chains/${s.chainId}`} className="muted">{s.chainName ?? s.chainId}</Link></td>
                  <td>{s.city ?? "—"}</td>
                  <td>{s.state ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
