// examples/SqlOS.Example.AngularWeb/src/app/pages/retail/chains/chains.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';
import { PagedResponse, ChainDto } from '../../../models';

@Component({
  selector: 'app-chains',
  standalone: true,
  imports: [RouterLink, FormsModule],
  template: `
    <div class="gap-20">
      <div class="page-header">
        <h1>Chains</h1>
        <p>Retail chains visible to your account.</p>
      </div>

      @if (error()) {
        <p class="error">{{ error() }}</p>
      }

      <div class="card">
        <div class="toolbar">
          <input type="text" placeholder="Search chains..." [ngModel]="search()" (ngModelChange)="onSearch($event)" class="toolbar-search">
          <button type="button" class="secondary" (click)="showCreate.set(!showCreate())">
            {{ showCreate() ? 'Cancel' : '+ Add Chain' }}
          </button>
        </div>

        @if (showCreate()) {
          <form (ngSubmit)="handleCreate()" class="create-form">
            <input type="text" placeholder="Chain name" [(ngModel)]="newName" name="newName" required autofocus>
            <input type="text" placeholder="Description (optional)" [(ngModel)]="newDesc" name="newDesc">
            <input type="text" placeholder="Headquarters address (optional)" [(ngModel)]="newHq" name="newHq">
            <button type="submit" [disabled]="creating()">{{ creating() ? 'Creating...' : 'Create Chain' }}</button>
          </form>
        }

        @if (loading()) {
          <p class="muted" style="margin-top: 16px">Loading...</p>
        } @else if (chains().length === 0) {
          <div class="empty-state">
            <strong>No chains found</strong>
            <p>{{ search() ? 'Try a different search term.' : 'No chains visible with your current permissions.' }}</p>
          </div>
        } @else {
          <table class="data-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th class="text-right">Locations</th>
              </tr>
            </thead>
            <tbody>
              @for (c of chains(); track c.id) {
                <tr>
                  <td><a [routerLink]="'/retail/chains/' + c.id">{{ c.name }}</a></td>
                  <td class="muted">{{ c.description ?? '—' }}</td>
                  <td class="text-right"><span class="badge badge-neutral">{{ c.locationCount }}</span></td>
                </tr>
              }
            </tbody>
          </table>
        }
      </div>
    </div>
  `,
})
export class ChainsComponent implements OnInit {
  private api = inject(ApiService);

  chains = signal<ChainDto[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);
  search = signal('');
  showCreate = signal(false);
  creating = signal(false);

  newName = '';
  newDesc = '';
  newHq = '';

  ngOnInit() {
    this.loadChains();
  }

  onSearch(value: string) {
    this.search.set(value);
    this.loadChains();
  }

  async loadChains() {
    this.loading.set(true);
    const params = new URLSearchParams({ pageSize: '50' });
    if (this.search()) params.set('search', this.search());
    try {
      const r = await this.api.get<PagedResponse<ChainDto>>(`/api/chains?${params}`);
      this.chains.set(r.data);
    } catch (e: any) {
      this.error.set(e.message);
    } finally {
      this.loading.set(false);
    }
  }

  async handleCreate() {
    if (!this.newName.trim()) return;
    this.creating.set(true);
    this.error.set(null);
    try {
      await this.api.post('/api/chains', {
        name: this.newName.trim(),
        description: this.newDesc.trim() || null,
        headquartersAddress: this.newHq.trim() || null,
      });
      this.newName = ''; this.newDesc = ''; this.newHq = '';
      this.showCreate.set(false);
      await this.loadChains();
    } catch (e: any) {
      this.error.set(e.message);
    } finally {
      this.creating.set(false);
    }
  }
}

// examples/SqlOS.Example.ExpoApp/app/(app)/chains/index.tsx
import { useEffect, useState, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  Pressable,
  TextInput,
  ActivityIndicator,
  RefreshControl,
  Alert,
} from "react-native";
import { useRouter } from "expo-router";
import { apiGet, apiPost } from "../../../services/api";
import { Colors } from "../../../services/theme";
import { Badge } from "../../../components/Badge";
import type { PagedResponse, ChainDto } from "../../../services/types";

export default function ChainsScreen() {
  const router = useRouter();
  const [chains, setChains] = useState<ChainDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDesc, setNewDesc] = useState("");

  const loadChains = useCallback(async () => {
    const params = new URLSearchParams({ pageSize: "50" });
    if (search) params.set("search", search);
    try {
      const r = await apiGet<PagedResponse<ChainDto>>(`/api/chains?${params}`);
      setChains(r.data);
    } catch {}
  }, [search]);

  useEffect(() => {
    setLoading(true);
    loadChains().finally(() => setLoading(false));
  }, [loadChains]);

  async function handleCreate() {
    if (!newName.trim()) return;
    setCreating(true);
    try {
      await apiPost("/api/chains", {
        name: newName.trim(),
        description: newDesc.trim() || null,
      });
      setNewName("");
      setNewDesc("");
      setShowCreate(false);
      await loadChains();
    } catch (e: any) {
      Alert.alert("Error", e.message);
    } finally {
      setCreating(false);
    }
  }

  return (
    <View style={styles.container}>
      <View style={styles.toolbar}>
        <TextInput
          style={styles.searchInput}
          placeholder="Search chains..."
          placeholderTextColor={Colors.textTertiary}
          value={search}
          onChangeText={setSearch}
        />
        <Pressable
          style={styles.addBtn}
          onPress={() => setShowCreate(!showCreate)}
        >
          <Text style={styles.addBtnText}>
            {showCreate ? "Cancel" : "+ Add"}
          </Text>
        </Pressable>
      </View>

      {showCreate && (
        <View style={styles.createForm}>
          <TextInput
            style={styles.input}
            placeholder="Chain name"
            placeholderTextColor={Colors.textTertiary}
            value={newName}
            onChangeText={setNewName}
            autoFocus
          />
          <TextInput
            style={styles.input}
            placeholder="Description (optional)"
            placeholderTextColor={Colors.textTertiary}
            value={newDesc}
            onChangeText={setNewDesc}
          />
          <Pressable
            style={[styles.submitBtn, creating && { opacity: 0.5 }]}
            onPress={handleCreate}
            disabled={creating}
          >
            <Text style={styles.submitBtnText}>
              {creating ? "Creating..." : "Create Chain"}
            </Text>
          </Pressable>
        </View>
      )}

      {loading ? (
        <ActivityIndicator
          style={{ marginTop: 40 }}
          color={Colors.primary}
          size="large"
        />
      ) : (
        <FlatList
          data={chains}
          keyExtractor={(c) => c.id}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={async () => {
                setRefreshing(true);
                await loadChains();
                setRefreshing(false);
              }}
            />
          }
          contentContainerStyle={{ paddingBottom: 40 }}
          ListEmptyComponent={
            <View style={styles.empty}>
              <Text style={styles.emptyTitle}>No chains found</Text>
              <Text style={styles.emptyDesc}>
                {search
                  ? "Try a different search."
                  : "No chains visible with your permissions."}
              </Text>
            </View>
          }
          renderItem={({ item }) => (
            <Pressable
              style={styles.row}
              onPress={() =>
                router.push(`/(app)/chains/${item.id}`)
              }
            >
              <View style={{ flex: 1 }}>
                <Text style={styles.rowTitle}>{item.name}</Text>
                {item.description && (
                  <Text style={styles.rowDesc}>{item.description}</Text>
                )}
              </View>
              <Badge variant="neutral">{item.locationCount}</Badge>
            </Pressable>
          )}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bg },
  toolbar: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchInput: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
  },
  addBtn: {
    backgroundColor: Colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  addBtnText: { fontSize: 13, fontWeight: "600", color: Colors.primary },
  createForm: {
    marginHorizontal: 16,
    padding: 16,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 10,
    marginBottom: 8,
  },
  input: {
    backgroundColor: Colors.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  submitBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  submitBtnText: { color: "#fff", fontWeight: "600", fontSize: 14 },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  rowTitle: { fontSize: 15, fontWeight: "600" },
  rowDesc: { fontSize: 13, color: Colors.textSecondary, marginTop: 1 },
  empty: { padding: 40, alignItems: "center" },
  emptyTitle: { fontSize: 15, fontWeight: "700", marginBottom: 4 },
  emptyDesc: { fontSize: 13, color: Colors.textSecondary, textAlign: "center" },
});
